 language: java
jdk:
- openjdk7
#- oraclejdk7
#- oraclejdk8
env:
  global:
  - secure: U4T6MOzC8a2hz36I7rAVOIUmoQbJ7c9sHF8W3Epf9tMLUcstG7RN3Kr2LAuGsSD9Nlgr0AY60SMSqOHNXedyT43n3fW0LVDF2+/HMl5ZWWCiTreaq11PgYKEuLHmAq5RAagiLiPFfT5JOiSs5FnOTM0n6795jkwM4UvU1Ob7DKU=
  - secure: OxWIPXLv+52nEBL4+sYyba8kPpihu2EPvitZ54g4SrJV0o29VDhFegJdx9FAAXAfh8NGJ1YozkMm2P+J2crylZYplHrF4Dvi7Gf9DDGLAKlc5Mf3Xb+toWwrYXFnoEr6LGGqwCCo1TJ15wfMUrRaUJucWkDi4ZhFt/TN/MAry74=
 
addons:
  sauce_connect: true